version: '3'
services:
  app:
    environment:
      - NODE_ENV=development
      - APP_PORT=3000
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    command: yarn run dev
