version: '3'
services:
  app:
    environment:
      - NODE_ENV=development
    build:
      context: .
      args:
        - APP_PORT=30001
    ports:
      - "30001:30001"
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    command: yarn run dev
